dist: xenial
addons:
  chrome: stable
  firefox: latest
language: node_js
node_js:
  - "node"
services:
  - xvfb
cache: npm
install:
  - npm prune
  - npm install
  - npm update
script:
  - npm run lint || travis_terminate 1
  - npm run build || travis_terminate 1
  - npm run test
  - npm run doc
